<?php
require_once("Util.php");

class Items extends Util{
    
    
    public function __construct() {
    }
    
    public function __destruct(){
    }
    
    public static function getTest(){
        return  array(
                        1=>'a'
                    );
    }
    
    public static function getTypeList(){
        return array(
                "encoding",
                "decoding",
                );
    }
    
    
    
    public static function getLaguageList(){
        return array(
                "PHP",
                "SQL",
                "JavaScript",
                "JavaScript (Rails)",
                "jQuery (JavaScript)",
                "JSON",
                "HTML",
                "Shell Script (Bash)",
                
                
                "Active4D",
                "Active4D Config",
                "Active4D Library",
                "Ada",
                "Ant",
                "ANTLR",
                "Apache",
                "AppleScript",
                "ASP",
                "ASP vb.NET",
                
                "BibTeX",
                "Bison",
                "Blog — HTML",
                "Blog — Markdown",
                "Blog — Text",
                "Blog — Textile",
                "Bulletin Board",
                "C",
                "C++",
                "C++ Qt",
                "camlp4",
                "CMake Listfile",
                "ColdFusion",
                "Context Free",
                "CSS",
                "CSV",
                "D",
                "DokuWiki",
                "Doxygen",
                "Dylan",
                "Eiffel",
                "Erlang",
                "F-Script",
                "Fortran - Modern",
                "Fortran - Punchcard",
                "FXScript",
                "Gettext",
                "Grails Server Page",
                "Graphviz (DOT)",
                "Greasemonkey",
                "Gri",
                "Groovy",
                "GTD",
                "GTDalt",
                "Haskell",
                
                "HTML (Active4D)",
                "HTML (ASP)",
                "HTML (ASP.net)",
                "HTML (Django)",
                "HTML (Erlang)",
                "HTML (Mason)",
                "HTML (Rails)",
                "HTML (Tcl)",
                "HTML (Template Toolkit)",
                "iCalendar",
                "Inform",
                "Ini",
                "Installer Distribution Script",
                "Io",
                "Java",
                "JavaDoc",
                "Java Properties",
                
                "Prototype &amp; Script.aculo.us (JavaScript)",
                "Javascript YUI",
                "Java Server Page (JSP)",
                "JSFL",
                
                "JUnit Test Report",
                "Language Grammar",
                "LaTeX",
                "LaTeX Beamer",
                "LaTeX Log",
                "LaTeX Memoir",
                "LaTeX Rdaemon",
                "Lex/Flex",
                "Lid File",
                "Lighttpd",
                "LilyPond",
                "Lisp",
                "Literate Haskell",
                "Logo",
                "Logtalk",
                "Lua",
                "MacPorts Portfile",
                "Mail",
                "Makefile",
                "Makegen",
                "Man",
                "Markdown",
                "MATLAB",
                "Maven POM",
                "Mediawiki",
                "MEL",
                "MIPS Assembler",
                "Modula-3",
                "mod_perl",
                "MoinMoin",
                "MooTools",
                "Movable Type",
                "Movable Type (MT only)",
                "MultiMarkdown",
                "Objective-C",
                "Objective-C++",
                "Objective-J",
                "OCaml",
                "OCamllex",
                "OCamlyacc",
                "Octave",
                "OpenGL",
                "Pascal",
                "Perl",
                "Perl HTML-Template",
                "Plain Text",
                "PmWiki",
                "Postscript",
                "Processing",
                "Prolog",
                "Property List",
                "Prototype &amp; Script.aculo.us (JavaScript) Bracketed",
                "Python",
                "Python Django",
                "qmake Project file",
                "Quake Style .cfg",
                "R",
                "Ragel",
                "R Console (R.app)",
                "R Console (Rdaemon)",
                "R Console (Rdaemon) Plain",
                "Rd (R Documentation)",
                "Regular Expressions (Oniguruma)",
                "Regular Expressions (Python)",
                "Release Notes",
                "Remind",
                "reStructuredText",
                "Rez",
                "RJS",
                "Ruby",
                "Ruby Haml",
                "Ruby on Rails",
                "S5 Slide Show",
                "Scala",
                "Scheme",
                "Scilab",
                "Setext",
                "Slate",
                "Smarty",
                
                "SQL (Rails)",
                "SSH Config",
                "Standard ML",
                "Standard ML - CM",
                "Strings File",
                "svn-commit.tmp",
                "SWeave",
                "SWIG",
                "Tcl",
                "TeX",
                "TeX Math",
                "Textile",
                "Thrift",
                "TSV",
                "Twiki",
                "Txt2tags",
                "Vectorscript",
                "XML",
                "XML strict",
                "XSL",
                "YAML",
            );
    }
}
